(define safe-divider (lambda (numerator)
                         (lambda (denominator)
                           (if (= denominator 0)
                               (display "cow")
                               (/ numerator denominator)))))